server:
  port: 8084
bot:
  name: R2xhZFN1Z3JvYl9ib3Q=
  token: MTcyNzgyMzY2OTpBQUVwZy1UOE5qalVuLTh4djR2R21kcjMxSDJPMnVURUx5Zw==
spring:
  main.allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate.ddl-auto: none
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    default-schema: bot
    liquibase-schema: bot
#    clear-checksums: true